#!/bin/bash

echo -e "\033[0;32mRemoving Unused Imports (autoflake):\033[0m"
echo
./venv/bin/autoflake --in-place --recursive starlette_early_data.py test.py setup.py
echo "----------"

echo -e "\033[0;32mLinting (black):\033[0m"
echo
./venv/bin/black --target-version=py37 starlette_early_data.py test.py setup.py
echo "----------"

echo -e "\033[0;32mSorting Imports (isort):\033[0m"
echo
./venv/bin/isort --project=starlette_early_data starlette_early_data.py test.py setup.py
echo "----------"

echo -e "\033[0;32mStatic Types Check After Linting (mypy):\033[0m"
echo
./venv/bin/mypy starlette_early_data.py --show-error-codes
echo "----------"