#!/bin/bash
set -e


find ./ -type f -name "*.py[co]" -delete
find ./ -type d -name __pycache__ -delete

rm -rf dist build starlette_early_data.egg-info

python3 setup.py sdist bdist_wheel
twine upload dist/*

rm -rf dist build starlette_early_data.egg-info
